name: Update voter team

on:
  push:
    branches:
      - main
    # Prevent infinite loops when this action pushes commits
    paths-ignore:
      - scripts/invited.txt

# This workflow changes state, we shouldn't run multiple at the same time!
concurrency:
  group: ${{ github.workflow }}
  # Canceling could leave us in a bad state
  cancel-in-progress: false

jobs:
  update-voter-team:
    runs-on: ubuntu-latest
    name: Update voter team
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          # https://github.com/actions/create-github-app-token/issues/172
          git config --global user.name 'nix-elections[bot]'
          git config --global user.email '181651500+nix-elections[bot]@users.noreply.github.com'

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - uses: cachix/install-nix-action@v27

      - name: Update team
        run: ./scripts/update-voter-team.sh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          ORG: ${{ github.repository_owner }}
          VOTER_TEAM: ${{ vars.VOTER_TEAM }}
